#include "src/game/envfx_snow.h"

const GeoLayout Wario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 32, 0, Wario_Hips_mesh),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 21, -2, 0, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Left_leg_1_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 10, 0, Wario_Left_leg_2_mesh),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(1, 0, 13, -1, -92, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Left_foot_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(1, -21, -2, 0, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Right_leg_1_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 10, 0, Wario_Right_leg_2_mesh),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(1, 0, 13, -1, -92, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Right_foot_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(4, 0, 30, 0, Wario_Torso_mesh),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(1, 0, 9, 25, -90, 0, -180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(4, 0, 0, 0, Wario_Buttons_mesh),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(1, 0, 44, 0, Wario_Head_mesh),
					GEO_TRANSLATE_ROTATE(1, 39, 24, 0, -90, 0, -90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Left_arm_1_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 22, 0, Wario_Left_arm_2_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 21, 0, 1, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Left_hand_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(1, -39, 24, 0, -90, 0, 90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Right_arm_1_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 22, 0, Wario_Right_arm_2_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 21, 0, 1, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, Wario_Right_hand_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, Wario_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, Wario_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, Wario_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, Wario_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, Wario_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, Wario_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, Wario_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, Wario_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
